framework:
    secret: '%env(WEBSITE_APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    cache:
        # The app cache caches to the filesystem by default. Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
