security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        admins:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            provider: admins
            pattern: ^/secured-area
            form_login:
                login_path: app_login
                check_path: app_login_check
                default_target_path: app_admin_home
                always_use_default_target_path: true
            logout:
                path: app_logout
                target: app_login

        website:
            pattern: ^/
            anonymous: true

    access_control:
        - { path: ^/secured-area, roles: ROLE_ADMIN }
