version: '2'

networks:
    # local network
    local:
        external: true

    # Internal & Stub
    default:

services:
    php:
        build: docker/php
        working_dir: /var/www/app
        networks:
            local:
                aliases:
                    - php
            default:
                aliases:
                    - php.local
        volumes:
            - .:/var/www/app
            - ~/.composer:/var/www/.composer
        depends_on:
            - db

    web:
        image: nginx:1-alpine
        networks:
            local:
                aliases:
                    - nicolas-dewez
            default:
                aliases:
                    - nicolas-dewez.local
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app
            - ./var/logs/nginx/:/var/log/nginx
        expose:
            - 80
        depends_on:
            - php

    db:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            local:
                aliases:
                    - db
            default:
                aliases:
                    - db.local
        volumes:
            - ./docker/db:/usr/local/src

    mailcatcher:
        image: zolweb/docker-mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
