version: '2'

networks:
    website:
        external: true

services:
    app:
        build: docker/app
        working_dir: /var/www/app
        environment:
            XDEBUG_ENABLED: 1
        env_file:
            - .env
        networks:
            website:
                aliases:
                    - app
        volumes:
            - .:/var/www/app
            - ~/.composer:/var/www/.composer
        depends_on:
            - db

    web:
        image: nginx:1-alpine
        networks:
            website:
                aliases:
                    - web
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app:ro
        expose:
            - 80
        depends_on:
            - app

    db:
        image: mysql:5.5
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            website:
                aliases:
                    - db
        volumes:
            - ./docker/db:/usr/local/src

    mailcatcher:
        image: zolweb/docker-mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
           website:
               aliases:
                   - mailer
